import Link from "next/link"

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900">
      <div className="absolute inset-0 bg-[url('/noise.png')] opacity-20 mix-blend-overlay"></div>
      
      {/* Header */}
      <header className="relative z-10 border-b border-purple-500/30 bg-black/90 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-purple-500 to-cyan-500 flex items-center justify-center">
                <span className="text-white font-bold text-lg">C</span>
              </div>
              <div>
                <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                  CODE HOMIE
                </h1>
              </div>
            </Link>
            
            <nav className="flex items-center gap-6">
              <Link href="/pricing" className="text-gray-400 hover:text-purple-400 transition-colors font-semibold">
                Pricing
              </Link>
              <Link href="/dashboard" className="text-gray-400 hover:text-purple-400 transition-colors font-semibold">
                Dashboard
              </Link>
            </nav>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="relative z-10 max-w-4xl mx-auto px-4 py-16">
        <div className="bg-black/40 backdrop-blur-sm rounded-2xl border border-purple-500/30 p-8">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent mb-8">
            Terms of Service
          </h1>
          
          <div className="prose prose-invert max-w-none">
            <p className="text-gray-300 text-lg mb-6">
              Last updated: {new Date().toLocaleDateString()}
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-300 mb-4">
              By accessing and using Code Homie, you accept and agree to be bound by the terms and provision of this agreement.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">2. Service Description</h2>
            <p className="text-gray-300 mb-4">
              Code Homie is an AI-powered coding assistant that provides code generation, review, and development tools.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">3. User Accounts</h2>
            <p className="text-gray-300 mb-4">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">4. Payment Terms</h2>
            <p className="text-gray-300 mb-4">
              Subscription fees are billed in advance and are non-refundable. You may cancel your subscription at any time.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">5. Acceptable Use</h2>
            <p className="text-gray-300 mb-4">
              You agree not to use the service for any unlawful purpose or in any way that could damage, disable, or impair the service.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">6. Intellectual Property</h2>
            <p className="text-gray-300 mb-4">
              Code generated by our service is provided to you under a permissive license. You retain ownership of code you create using our tools.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">7. Limitation of Liability</h2>
            <p className="text-gray-300 mb-4">
              Code Homie shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">8. Contact Information</h2>
            <p className="text-gray-300 mb-4">
              For questions about these Terms of Service, please contact us through our support channels.
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="relative z-10 border-t border-purple-500/30 bg-black/90 backdrop-blur-sm mt-16">
        <div className="max-w-7xl mx-auto px-4 py-8">
          <div className="text-center">
            <p className="text-purple-500/70 text-sm">
              Code Homie | Professional AI Coding Assistant
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}